### ISSUE TITLE
CircleCI and codecov

### ISSUE THREAD

**Issue by Sweetchuck** [mindscreen/yarnlock#7]
Some initial setup is required on 
 * [CircleCI](https://app.circleci.com/projects/project-dashboard/github/mindscreen/)
 * [codecov](https://app.codecov.io/gh/mindscreen/yarnlock/settings)

Codecov provides a token and it has to be added on CircleCI as `CODECOV_TOKEN` environment variable.

On the WebUI of CircleCI a build can be trigger manually for a branch.
Currently the badge says: "No builds"

**Comment by PRGfx** [comment]
Thank you for your advice.
