### ISSUE TITLE
Parser::splitVersionString does not handle Git URLs used as dependencies/versions correctly

### ISSUE THREAD

**Issue by InvisibleSmiley** [mindscreen/yarnlock#9]
Currently the description of `Parser::splitVersionString` reads:

> To avoid splitting on scoped package-names, every but the last @ are considered package name.

This does not suffice when it comes to Git URLs used as dependencies/versions which themselves may contain @ to separate user (or credentials in general) from host/rest.

Cf. https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies

Consider the following examples:
- `@foo/bar@git+ssh://user@host:1234/foo/bar#semver:^1.2.3` should be split into `@foo/bar` and `^1.2.3`
- `@foo/bar@git://user@host/foo/bar.git#v1.2.3` should be split into `@foo/bar` and `v1.2.3`

Suggested fix:
```php
public static function splitVersionString($versionString)
{
    // Scoped package names start with an "@" → skip the first character.
    // Note: $versionString may contain even more than two "@" if version is "protocol://user@host..."
    $location = strpos($versionString, '@', 1);
    if ($location > 0) {
        $name = substr($versionString, 0, $location);
        $version = substr($versionString, $location + 1);
        // Handle special cases that package.json allows for "Git URLs as Dependencies"
        if (preg_match('/#(semver:)?(.+)$/', $version, $matches) === 1) {
            $version = $matches[2];
        }
        return [$name, $version];
    }
    throw new \InvalidArgumentException('Version string is expected to contain "@" separating name from version.');
}
```

**Comment by PRGfx** [comment]
Hi @InvisibleSmiley, I see where the current implementation fails, but I don't think there should be special handling for the refs given on git URLs: to my understanding the source of the installation is important (for example when installing from a fork).
If you want, you can create a PR to fix the splitting, otherwise I will try to get to it this week.
